name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/checkout@v3
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: car-management-app # the name of the project on Deno Deploy
          entrypoint: src/app.js # the entrypoint to deploy
